### ISSUE TITLE
USER STORY: Love Running user story tasks

### ISSUE THREAD

**Issue by Charte-dot** [Charte-dot/My-First-Agile-Project#6]
In order to provide anonymous feedback as a user, I can choose to hide my identity in the poll response.

Acceptance Criteria:

- The option should be provided as a checkbox
- The checkbox should be checked by default
- The option should appear next to the submission button
  
# Acceptance Criteria:

The option should be provided as a checkbox
The checkbox should be checked by default
The option should appear next to the submission button
  
# Tasks
  - [x] Update the View: the poll design(HTML & CSS) to include checkbox and to show the name of the submitter
  - [ ] Create a new field on the model to track the user name
  - [ ]  Update the controller function
  - [ ]  Update Unit test scripts
  - [ ] Test functionality
