### ISSUE TITLE
USER STORY: Love running admin

### ISSUE THREAD

**Issue by Charte-dot** [Charte-dot/My-First-Agile-Project#8]
In order to automatically hide the poll as an administrator, I can pick the expiry date while publishing the poll.
  
# Acceptance Criteria:
  a. The poll should disappear at 11.59 PM on the target date 
  b. The real estate of the "Poll" should be reserved on the home page. A message that says "Stay Tuned, a new poll is coming soon" 
      should appear if no other poll is active.
  c. The administrator expiry date should be at least 3 days after the current date.
  
# Tasks
  - [x] Update the admin module view: the poll design(HTML & CSS) to include date picker. 
  - [ ] Update a JavaScript function to validate the expiry date is at least after 3 days.
  - [ ] Create a job to check expired polls everyday at 11.59 PM and hide them
  - [ ] Update controller function
  - [ ] update unit test scripts
  - [ ] Test the functionality
